2018-06-27 21:09:06,543 - main.py[line:48] - INFO: words index loaded...
2018-06-27 21:09:06,558 - tf_logging.py[line:82] - INFO: Using config: {'_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E0FAC47400>, '_is_chief': True, '_keep_checkpoint_max': 1, '_save_summary_steps': 100, '_log_step_count_steps': 100, '_task_type': 'worker', '_num_worker_replicas': 1, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_model_dir': './model/saved_model/model_1000', '_session_config': None, '_tf_random_seed': None, '_num_ps_replicas': 0, '_service': None}
2018-06-27 21:09:08,935 - tf_logging.py[line:82] - INFO: Create CheckpointSaverHook.
2018-06-27 21:09:19,741 - tf_logging.py[line:82] - INFO: Saving checkpoints for 1 into ./model/saved_model/model_1000\model.ckpt.
2018-06-27 21:09:21,857 - tf_logging.py[line:82] - INFO: step = 1, loss = 1.3867334
2018-06-27 21:09:21,857 - tf_logging.py[line:82] - INFO: global_step = 1, lr = 0.0005
2018-06-27 21:09:32,167 - tf_logging.py[line:82] - INFO: Saving checkpoints for 100 into ./model/saved_model/model_1000\model.ckpt.
2018-06-27 21:09:34,341 - tf_logging.py[line:82] - INFO: Loss for final step: 1.4602498.
2018-06-27 21:09:34,342 - main.py[line:30] - INFO: evaluating model on 1000 data samples....
2018-06-27 21:09:36,537 - tf_logging.py[line:82] - INFO: Starting evaluation at 2018-06-27-20:09:36
2018-06-27 21:09:36,942 - tf_logging.py[line:82] - INFO: Restoring parameters from ./model/saved_model/model_1000\model.ckpt-100
2018-06-27 21:09:39,511 - tf_logging.py[line:82] - INFO: Finished evaluation at 2018-06-27-20:09:39
2018-06-27 21:09:39,511 - tf_logging.py[line:82] - INFO: Saving dict for global step 100: accuracy = 0.421875, confusion_matrix = [[  0  90   0   0]
 [  0 135   0   0]
 [  0  72   0   0]
 [  0  23   0   0]], global_step = 100, loss = 1.2951396
2018-06-27 21:09:42,659 - tf_logging.py[line:86] - WARNING: Skipping summary for confusion_matrix, must be a float, np.float32, np.int64, np.int32 or int.
2018-06-27 21:09:42,713 - main.py[line:32] - INFO: Val set accuracy: 0.422

2018-06-27 21:09:42,714 - tf_logging.py[line:82] - INFO: Using config: {'_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E0F8130940>, '_is_chief': True, '_keep_checkpoint_max': 1, '_save_summary_steps': 100, '_log_step_count_steps': 100, '_task_type': 'worker', '_num_worker_replicas': 1, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_model_dir': './model/saved_model/model_2000', '_session_config': None, '_tf_random_seed': None, '_num_ps_replicas': 0, '_service': None}
2018-06-27 21:09:45,113 - tf_logging.py[line:82] - INFO: Create CheckpointSaverHook.
2018-06-27 21:09:53,305 - tf_logging.py[line:82] - INFO: Saving checkpoints for 1 into ./model/saved_model/model_2000\model.ckpt.
2018-06-27 21:09:55,233 - tf_logging.py[line:82] - INFO: step = 1, loss = 1.3867546
2018-06-27 21:09:55,233 - tf_logging.py[line:82] - INFO: global_step = 1, lr = 0.0005
2018-06-27 21:10:05,993 - tf_logging.py[line:82] - INFO: global_step/sec: 9.26682
2018-06-27 21:10:05,993 - tf_logging.py[line:82] - INFO: step = 101, loss = 1.195353 (10.760 sec)
2018-06-27 21:10:05,993 - tf_logging.py[line:82] - INFO: global_step = 101, lr = 0.0004974419 (10.760 sec)
2018-06-27 21:10:16,642 - tf_logging.py[line:82] - INFO: Saving checkpoints for 200 into ./model/saved_model/model_2000\model.ckpt.
2018-06-27 21:10:19,070 - tf_logging.py[line:82] - INFO: Loss for final step: 1.3111454.
2018-06-27 21:10:19,070 - main.py[line:30] - INFO: evaluating model on 2000 data samples....
2018-06-27 21:10:20,870 - tf_logging.py[line:82] - INFO: Starting evaluation at 2018-06-27-20:10:20
2018-06-27 21:10:21,198 - tf_logging.py[line:82] - INFO: Restoring parameters from ./model/saved_model/model_2000\model.ckpt-200
2018-06-27 21:10:23,732 - tf_logging.py[line:82] - INFO: Finished evaluation at 2018-06-27-20:10:23
2018-06-27 21:10:23,732 - tf_logging.py[line:82] - INFO: Saving dict for global step 200: accuracy = 0.428125, confusion_matrix = [[ 0 57 33  0]
 [ 0 96 39  0]
 [ 0 31 41  0]
 [ 0  4 19  0]], global_step = 200, loss = 1.2940505
2018-06-27 21:10:26,498 - tf_logging.py[line:86] - WARNING: Skipping summary for confusion_matrix, must be a float, np.float32, np.int64, np.int32 or int.
2018-06-27 21:10:26,555 - main.py[line:32] - INFO: Val set accuracy: 0.428

2018-06-27 21:10:26,555 - tf_logging.py[line:82] - INFO: Using config: {'_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E0FAC38DD8>, '_is_chief': True, '_keep_checkpoint_max': 1, '_save_summary_steps': 100, '_log_step_count_steps': 100, '_task_type': 'worker', '_num_worker_replicas': 1, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_model_dir': './model/saved_model/model_3000', '_session_config': None, '_tf_random_seed': None, '_num_ps_replicas': 0, '_service': None}
2018-06-27 21:10:28,441 - tf_logging.py[line:82] - INFO: Create CheckpointSaverHook.
2018-06-27 21:10:36,242 - tf_logging.py[line:82] - INFO: Saving checkpoints for 1 into ./model/saved_model/model_3000\model.ckpt.
2018-06-27 21:10:38,202 - tf_logging.py[line:82] - INFO: step = 1, loss = 1.386812
2018-06-27 21:10:38,202 - tf_logging.py[line:82] - INFO: global_step = 1, lr = 0.0005
2018-06-27 21:10:48,712 - tf_logging.py[line:82] - INFO: global_step/sec: 9.50058
2018-06-27 21:10:48,712 - tf_logging.py[line:82] - INFO: step = 101, loss = 1.2215223 (10.510 sec)
2018-06-27 21:10:48,712 - tf_logging.py[line:82] - INFO: global_step = 101, lr = 0.0004974419 (10.510 sec)
2018-06-27 21:10:58,981 - tf_logging.py[line:82] - INFO: global_step/sec: 9.73849
2018-06-27 21:10:58,982 - tf_logging.py[line:82] - INFO: step = 201, loss = 1.3124844 (10.271 sec)
2018-06-27 21:10:58,982 - tf_logging.py[line:82] - INFO: global_step = 201, lr = 0.0004948969 (10.271 sec)
2018-06-27 21:11:09,327 - tf_logging.py[line:82] - INFO: Saving checkpoints for 300 into ./model/saved_model/model_3000\model.ckpt.
2018-06-27 21:11:11,452 - tf_logging.py[line:82] - INFO: Loss for final step: 1.1145105.
2018-06-27 21:11:11,452 - main.py[line:30] - INFO: evaluating model on 3000 data samples....
2018-06-27 21:11:13,802 - tf_logging.py[line:82] - INFO: Starting evaluation at 2018-06-27-20:11:13
2018-06-27 21:11:14,114 - tf_logging.py[line:82] - INFO: Restoring parameters from ./model/saved_model/model_3000\model.ckpt-300
2018-06-27 21:11:16,511 - tf_logging.py[line:82] - INFO: Finished evaluation at 2018-06-27-20:11:16
2018-06-27 21:11:16,511 - tf_logging.py[line:82] - INFO: Saving dict for global step 300: accuracy = 0.43125, confusion_matrix = [[62 21  7  0]
 [67 44 24  0]
 [13 27 32  0]
 [ 8  1 14  0]], global_step = 300, loss = 1.2822195
2018-06-27 21:11:19,239 - tf_logging.py[line:86] - WARNING: Skipping summary for confusion_matrix, must be a float, np.float32, np.int64, np.int32 or int.
2018-06-27 21:11:19,318 - main.py[line:32] - INFO: Val set accuracy: 0.431

2018-06-27 21:11:19,318 - tf_logging.py[line:82] - INFO: Using config: {'_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E220AA74A8>, '_is_chief': True, '_keep_checkpoint_max': 1, '_save_summary_steps': 100, '_log_step_count_steps': 100, '_task_type': 'worker', '_num_worker_replicas': 1, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_model_dir': './model/saved_model/model_4000', '_session_config': None, '_tf_random_seed': None, '_num_ps_replicas': 0, '_service': None}
2018-06-27 21:11:21,114 - tf_logging.py[line:82] - INFO: Create CheckpointSaverHook.
2018-06-27 21:11:28,915 - tf_logging.py[line:82] - INFO: Saving checkpoints for 1 into ./model/saved_model/model_4000\model.ckpt.
2018-06-27 21:11:30,853 - tf_logging.py[line:82] - INFO: step = 1, loss = 1.3868186
2018-06-27 21:11:30,853 - tf_logging.py[line:82] - INFO: global_step = 1, lr = 0.0005
2018-06-27 21:11:41,594 - tf_logging.py[line:82] - INFO: global_step/sec: 9.31037
2018-06-27 21:11:41,594 - tf_logging.py[line:82] - INFO: step = 101, loss = 1.1709495 (10.741 sec)
2018-06-27 21:11:41,594 - tf_logging.py[line:82] - INFO: global_step = 101, lr = 0.0004974419 (10.741 sec)
2018-06-27 21:11:52,346 - tf_logging.py[line:82] - INFO: global_step/sec: 9.30086
2018-06-27 21:11:52,346 - tf_logging.py[line:82] - INFO: step = 201, loss = 1.281766 (10.752 sec)
2018-06-27 21:11:52,346 - tf_logging.py[line:82] - INFO: global_step = 201, lr = 0.0004948969 (10.752 sec)
2018-06-27 21:12:03,346 - tf_logging.py[line:82] - INFO: global_step/sec: 9.09088
2018-06-27 21:12:03,361 - tf_logging.py[line:82] - INFO: step = 301, loss = 1.1935835 (11.016 sec)
2018-06-27 21:12:03,361 - tf_logging.py[line:82] - INFO: global_step = 301, lr = 0.0004923649 (11.016 sec)
2018-06-27 21:12:13,795 - tf_logging.py[line:82] - INFO: Saving checkpoints for 400 into ./model/saved_model/model_4000\model.ckpt.
2018-06-27 21:12:15,843 - tf_logging.py[line:82] - INFO: Loss for final step: 1.2493782.
2018-06-27 21:12:15,843 - main.py[line:30] - INFO: evaluating model on 4000 data samples....
2018-06-27 21:12:17,749 - tf_logging.py[line:82] - INFO: Starting evaluation at 2018-06-27-20:12:17
2018-06-27 21:12:18,106 - tf_logging.py[line:82] - INFO: Restoring parameters from ./model/saved_model/model_4000\model.ckpt-400
2018-06-27 21:12:20,595 - tf_logging.py[line:82] - INFO: Finished evaluation at 2018-06-27-20:12:20
2018-06-27 21:12:20,595 - tf_logging.py[line:82] - INFO: Saving dict for global step 400: accuracy = 0.5875, confusion_matrix = [[62 17 11  0]
 [16 74 45  0]
 [ 3 17 52  0]
 [ 1  2 20  0]], global_step = 400, loss = 1.1526332
2018-06-27 21:12:23,447 - tf_logging.py[line:86] - WARNING: Skipping summary for confusion_matrix, must be a float, np.float32, np.int64, np.int32 or int.
2018-06-27 21:12:23,519 - main.py[line:32] - INFO: Val set accuracy: 0.587

2018-06-27 21:12:23,519 - tf_logging.py[line:82] - INFO: Using config: {'_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E0FAC40DD8>, '_is_chief': True, '_keep_checkpoint_max': 1, '_save_summary_steps': 100, '_log_step_count_steps': 100, '_task_type': 'worker', '_num_worker_replicas': 1, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_model_dir': './model/saved_model/model_5000', '_session_config': None, '_tf_random_seed': None, '_num_ps_replicas': 0, '_service': None}
2018-06-27 21:12:25,355 - tf_logging.py[line:82] - INFO: Create CheckpointSaverHook.
2018-06-27 21:12:33,049 - tf_logging.py[line:82] - INFO: Saving checkpoints for 1 into ./model/saved_model/model_5000\model.ckpt.
2018-06-27 21:12:35,074 - tf_logging.py[line:82] - INFO: step = 1, loss = 1.386835
2018-06-27 21:12:35,074 - tf_logging.py[line:82] - INFO: global_step = 1, lr = 0.0005
2018-06-27 21:12:46,452 - tf_logging.py[line:82] - INFO: global_step/sec: 8.78926
2018-06-27 21:12:46,452 - tf_logging.py[line:82] - INFO: step = 101, loss = 1.2063568 (11.378 sec)
2018-06-27 21:12:46,452 - tf_logging.py[line:82] - INFO: global_step = 101, lr = 0.0004974419 (11.378 sec)
2018-06-27 21:12:56,875 - tf_logging.py[line:82] - INFO: global_step/sec: 9.59425
2018-06-27 21:12:56,875 - tf_logging.py[line:82] - INFO: step = 201, loss = 1.2981645 (10.423 sec)
2018-06-27 21:12:56,875 - tf_logging.py[line:82] - INFO: global_step = 201, lr = 0.0004948969 (10.423 sec)
2018-06-27 21:13:07,535 - tf_logging.py[line:82] - INFO: global_step/sec: 9.38067
2018-06-27 21:13:07,551 - tf_logging.py[line:82] - INFO: step = 301, loss = 1.1676861 (10.676 sec)
2018-06-27 21:13:07,551 - tf_logging.py[line:82] - INFO: global_step = 301, lr = 0.0004923649 (10.676 sec)
2018-06-27 21:13:18,162 - tf_logging.py[line:82] - INFO: global_step/sec: 9.41009
2018-06-27 21:13:18,178 - tf_logging.py[line:82] - INFO: step = 401, loss = 1.0557365 (10.627 sec)
2018-06-27 21:13:18,178 - tf_logging.py[line:82] - INFO: global_step = 401, lr = 0.0004898459 (10.627 sec)
2018-06-27 21:13:28,397 - tf_logging.py[line:82] - INFO: Saving checkpoints for 500 into ./model/saved_model/model_5000\model.ckpt.
2018-06-27 21:13:30,424 - tf_logging.py[line:82] - INFO: Loss for final step: 1.1598594.
2018-06-27 21:13:30,424 - main.py[line:30] - INFO: evaluating model on 5000 data samples....
2018-06-27 21:13:32,400 - tf_logging.py[line:82] - INFO: Starting evaluation at 2018-06-27-20:13:32
2018-06-27 21:13:32,740 - tf_logging.py[line:82] - INFO: Restoring parameters from ./model/saved_model/model_5000\model.ckpt-500
2018-06-27 21:13:35,346 - tf_logging.py[line:82] - INFO: Finished evaluation at 2018-06-27-20:13:35
2018-06-27 21:13:35,346 - tf_logging.py[line:82] - INFO: Saving dict for global step 500: accuracy = 0.553125, confusion_matrix = [[54 26 10  0]
 [16 74 45  0]
 [ 1 22 49  0]
 [ 3  3 17  0]], global_step = 500, loss = 1.1825788
2018-06-27 21:13:38,225 - tf_logging.py[line:86] - WARNING: Skipping summary for confusion_matrix, must be a float, np.float32, np.int64, np.int32 or int.
2018-06-27 21:13:38,303 - main.py[line:32] - INFO: Val set accuracy: 0.553

2018-06-27 21:13:38,303 - tf_logging.py[line:82] - INFO: Using config: {'_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E0F34F0898>, '_is_chief': True, '_keep_checkpoint_max': 1, '_save_summary_steps': 100, '_log_step_count_steps': 100, '_task_type': 'worker', '_num_worker_replicas': 1, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_model_dir': './model/saved_model/model_5850', '_session_config': None, '_tf_random_seed': None, '_num_ps_replicas': 0, '_service': None}
2018-06-27 21:13:40,285 - tf_logging.py[line:82] - INFO: Create CheckpointSaverHook.
2018-06-27 21:13:48,179 - tf_logging.py[line:82] - INFO: Saving checkpoints for 1 into ./model/saved_model/model_5850\model.ckpt.
2018-06-27 21:13:50,190 - tf_logging.py[line:82] - INFO: step = 1, loss = 1.3870604
2018-06-27 21:13:50,190 - tf_logging.py[line:82] - INFO: global_step = 1, lr = 0.0005
2018-06-27 21:14:01,131 - tf_logging.py[line:82] - INFO: global_step/sec: 9.12768
2018-06-27 21:14:01,131 - tf_logging.py[line:82] - INFO: step = 101, loss = 1.1861622 (10.940 sec)
2018-06-27 21:14:01,131 - tf_logging.py[line:82] - INFO: global_step = 101, lr = 0.0004974419 (10.940 sec)
2018-06-27 21:14:11,514 - tf_logging.py[line:82] - INFO: global_step/sec: 9.63078
2018-06-27 21:14:11,515 - tf_logging.py[line:82] - INFO: step = 201, loss = 1.2898725 (10.384 sec)
2018-06-27 21:14:11,515 - tf_logging.py[line:82] - INFO: global_step = 201, lr = 0.0004948969 (10.384 sec)
2018-06-27 21:14:21,896 - tf_logging.py[line:82] - INFO: global_step/sec: 9.63178
2018-06-27 21:14:21,912 - tf_logging.py[line:82] - INFO: step = 301, loss = 1.2598951 (10.397 sec)
2018-06-27 21:14:21,912 - tf_logging.py[line:82] - INFO: global_step = 301, lr = 0.0004923649 (10.397 sec)
2018-06-27 21:14:32,400 - tf_logging.py[line:82] - INFO: global_step/sec: 9.52027
2018-06-27 21:14:32,416 - tf_logging.py[line:82] - INFO: step = 401, loss = 1.1830522 (10.504 sec)
2018-06-27 21:14:32,416 - tf_logging.py[line:82] - INFO: global_step = 401, lr = 0.0004898459 (10.504 sec)
2018-06-27 21:14:43,121 - tf_logging.py[line:82] - INFO: global_step/sec: 9.32782
2018-06-27 21:14:43,136 - tf_logging.py[line:82] - INFO: step = 501, loss = 1.3457245 (10.721 sec)
2018-06-27 21:14:43,136 - tf_logging.py[line:82] - INFO: global_step = 501, lr = 0.0004873397 (10.721 sec)
2018-06-27 21:14:52,176 - tf_logging.py[line:82] - INFO: Saving checkpoints for 585 into ./model/saved_model/model_5850\model.ckpt.
2018-06-27 21:14:54,275 - tf_logging.py[line:82] - INFO: Loss for final step: 0.9755744.
2018-06-27 21:14:54,275 - main.py[line:30] - INFO: evaluating model on 5850 data samples....
2018-06-27 21:14:56,526 - tf_logging.py[line:82] - INFO: Starting evaluation at 2018-06-27-20:14:56
2018-06-27 21:14:57,041 - tf_logging.py[line:82] - INFO: Restoring parameters from ./model/saved_model/model_5850\model.ckpt-585
2018-06-27 21:14:59,453 - tf_logging.py[line:82] - INFO: Finished evaluation at 2018-06-27-20:14:59
2018-06-27 21:14:59,453 - tf_logging.py[line:82] - INFO: Saving dict for global step 585: accuracy = 0.578125, confusion_matrix = [[62 17 11  0]
 [17 95 23  0]
 [ 5 39 28  0]
 [ 2  6 15  0]], global_step = 585, loss = 1.1682426
2018-06-27 21:15:02,375 - tf_logging.py[line:86] - WARNING: Skipping summary for confusion_matrix, must be a float, np.float32, np.int64, np.int32 or int.
2018-06-27 21:15:02,491 - main.py[line:32] - INFO: Val set accuracy: 0.578

